### PR TITLE
Donna

### PR DESCRIPTION
**Pull request by Donnastjames**
Removed unnecessary user-seed.js in seeds folder, updated gift-routes to refer to Gift instead of Gifts, added util/helper.js, and slight code clean up.

### CODE REVIEW

**Review by DannyRoubin — APPROVED** [review]
Looks great!

**Review by DannyRoubin — APPROVED** [review]
Great work!

**Review by DannyRoubin — APPROVED** [review]
Nicely done!

**Review by tylerhance — APPROVED** [review]
Looks good

**Review by CailinBellWold — APPROVED** [review]
Looks correct.

**Review by CailinBellWold — APPROVED** [review]
Looks correct. Tyler will update, too...

**Review by CailinBellWold — APPROVED** [review]

**Pull request merged**
