### PR TITLE
created the login and the logout js files, we may need to modify them

### PR DESCRIPTION
**Pull request by DannyRoubin**

### CODE REVIEW

**Review by CailinBellWold — APPROVED** [review]
Updated from profile to userlanding.

**Review by CailinBellWold — APPROVED** [review]
99% correct. Updated profile to userlanding in subsequent commit.

**Review by tylerhance — APPROVED** [review]
Changes look good. Approved!

**Review by tylerhance — APPROVED** [review]
Great job, approved!

**Review by Donnastjames — APPROVED** [review]
Looks good to me!

**Review by Donnastjames — APPROVED** [review]
Looks good!

**Pull request merged**
