### PR TITLE
Tyler routes feature

### PR DESCRIPTION
**Pull request by tylerhance**
Updated the path name from profile to userlanding. Added additional logic for creating user/gift data

### CODE REVIEW

**Review by DannyRoubin — APPROVED** [review]
It looks great!

**Review by CailinBellWold — APPROVED** [review]
Looks correct (deleted line one to correct merge conflict).

**Review by CailinBellWold — APPROVED** [review]
Looks correct. Updated homepage/landing page to userlanding.

**Review by CailinBellWold — APPROVED** [review]
Looks correct.

**Review by CailinBellWold — APPROVED** [review]
Looks correct. We removed the recipient model.

**Review by CailinBellWold — APPROVED** [review]
Looks correct. Updated gift/gifts,

**Review by Donnastjames — APPROVED** [review]
Looks good!

**Review by Donnastjames — APPROVED** [review]
Looks good!

**Review by Donnastjames — APPROVED** [review]
Looks good!

**Review by Donnastjames — APPROVED** [review]
Looks good!

**Review by Donnastjames — APPROVED** [review]
Looks good!

**Pull request merged**
